import React, { useEffect, useState } from 'react';
import { Bot, ExternalLink, ShoppingCart, Headphones, Target, Building2, Package, Wrench, LifeBuoy, CalendarCheck, CircleHelp, Store, ShoppingCart as CartIcon, House, Hotel, Plane, Utensils, Stethoscope, GraduationCap, WalletCards, ShieldCheck, Laptop, CloudCog, BriefcaseBusiness, Megaphone, UsersRound, Truck, CarFront, Scale, Dumbbell, UtensilsCrossed } from 'lucide-react';

const SUPABASE_URL = 'https://tlkmcfpzfdokcnyyvkov.supabase.co';
const SUPABASE_KEY = 'sb_publishable_-gNvioLExBonu8hGuWa8lQ_eIWmhMn6';

type Chatbot={id:string;name:string;slug:string;description?:string|null;enabled:boolean;embed_code?:string|null;logo_url?:string|null;brand_color?:string|null};
type Price={chatbot_id:string;plan_name:string;monthly_price:number;annual_price:number;highlighted?:boolean;enabled:boolean};

function getDemoSlug(bot:Chatbot){const code=bot.embed_code||'';const match=code.match(/data-chatbot\s*=\s*["']([^"']+)["']/i);return match?.[1]||bot.slug;}

const iconMap:Record<string,any>={'Customer Care Pro':Headphones,'Sales Assistant':Target,'LeadGen AI':Target,'Business Advisor':Building2,'Product Expert':Package,'Service Desk AI':Wrench,'Support Hero':LifeBuoy,'Booking Assistant':CalendarCheck,'FAQ Master':CircleHelp,'Retail Assistant':Store,'Ecommerce Guide':CartIcon,'Real Estate Advisor':House,'Hotel Concierge':Hotel,'Travel Planner':Plane,'Restaurant Host':Utensils,'Healthcare Reception':Stethoscope,'Education Advisor':GraduationCap,'Finance Support':WalletCards,'Insurance Assistant':ShieldCheck,'Tech Support AI':Laptop,'SaaS Sales Bot':CloudCog,'Agency Consultant':BriefcaseBusiness,'Marketing Assistant':Megaphone,'HR Helpdesk':UsersRound,'Logistics Assistant':Truck,'Automotive Advisor':CarFront,'Legal Reception':Scale,'Fitness Coach':Dumbbell,'Restaurant Sales Bot':UtensilsCrossed};

const iconColors:Record<string,string>={'Customer Care Pro':'#2563eb','Sales Assistant':'#16a34a','LeadGen AI':'#7c3aed','Business Advisor':'#0f766e','Product Expert':'#ea580c','Service Desk AI':'#475569','Support Hero':'#0284c7','Booking Assistant':'#db2777','FAQ Master':'#4f46e5','Retail Assistant':'#c2410c','Ecommerce Guide':'#0891b2','Real Estate Advisor':'#059669','Hotel Concierge':'#9333ea','Travel Planner':'#2563eb','Restaurant Host':'#dc2626','Healthcare Reception':'#0d9488','Education Advisor':'#4f46e5','Finance Support':'#15803d','Insurance Assistant':'#0369a1','Tech Support AI':'#334155','SaaS Sales Bot':'#7c3aed','Agency Consultant':'#b45309','Marketing Assistant':'#e11d48','HR Helpdesk':'#4f46e5','Logistics Assistant':'#ca8a04','Automotive Advisor':'#475569','Legal Reception':'#1e40af','Fitness Coach':'#16a34a','Restaurant Sales Bot':'#dc2626'};

export const ChatbotCatalog:React.FC<{onNavigateToContact?:(chatbotName:string)=>void}>=({onNavigateToContact})=>{
 const[bots,setBots]=useState<Chatbot[]>([]),[prices,setPrices]=useState<Price[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const load=async()=>{try{const headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY};const[botRes,priceRes]=await Promise.all([fetch(SUPABASE_URL+'/rest/v1/chatbots?select=id,name,slug,description,enabled,embed_code,logo_url,brand_color&enabled=eq.true&order=created_at.desc',{headers}),fetch(SUPABASE_URL+'/rest/v1/chatbot_prices?select=chatbot_id,plan_name,monthly_price,annual_price,highlighted,enabled&enabled=eq.true&order=sort_order.asc',{headers})]);if(!botRes.ok||!priceRes.ok)throw new Error('Could not load chatbots');setBots(await botRes.json());setPrices(await priceRes.json());}catch{setError('Chatbots could not be loaded right now.')}finally{setLoading(false)}};load()},[]);
 return <section className="px-4 sm:px-6 pt-5 pb-7">
  <div className="mb-5"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-[11px] font-bold uppercase tracking-wider">Available AI Chatbots</div><h2 className="font-headline text-2xl sm:text-3xl font-extrabold text-gray-900 mt-2">Choose a chatbot to test</h2></div>
  {loading&&<div className="rounded-2xl bg-white border p-6 text-sm text-gray-500">Loading chatbots…</div>}
  {error&&<div className="rounded-2xl bg-red-50 border border-red-100 p-6 text-sm text-red-700">{error}</div>}
  {!loading&&!error&&bots.length===0&&<div className="rounded-2xl bg-white border p-6 text-sm text-gray-500">No enabled chatbots yet.</div>}
  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{bots.map(bot=>{const botPrices=prices.filter(p=>p.chatbot_id===bot.id);const cheapest=botPrices.length?Math.min(...botPrices.map(p=>Number(p.monthly_price))):null;const demoSlug=getDemoSlug(bot);const Icon=iconMap[bot.name]||Bot;const iconColor=iconColors[bot.name]||bot.brand_color||'#111827';return <article key={bot.id} className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5 flex flex-col">
   <div className="flex items-start justify-between gap-3"><div className="w-14 h-14 rounded-2xl flex items-center justify-center overflow-hidden bg-white border-2 shadow-sm" style={{color:iconColor,borderColor:iconColor+"33",backgroundColor:iconColor+"0D"}}>{bot.logo_url?<img src={bot.logo_url} alt={bot.name} className="w-full h-full object-contain bg-white p-2"/>:<Icon size={30} strokeWidth={2.4}/>}</div><span className="text-[10px] font-bold uppercase tracking-wide text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">Live Demo</span></div>
   <h3 className="font-bold text-lg text-gray-900 mt-4">{bot.name}</h3><p className="text-sm text-gray-600 mt-1 min-h-[40px]">{bot.description||'AI chatbot for sales and customer support.'}</p>
   <div className="mt-4 flex items-end justify-between gap-3"><div>{cheapest!==null?<><span className="text-xs text-gray-500">Starting from</span><div className="font-extrabold text-xl text-gray-900">{'$'}{cheapest}<span className="text-xs font-medium text-gray-500">/mo</span></div></>:<span className="text-sm text-gray-500">Pricing available on request</span>}</div>
    <div className="flex gap-2"><a href={`/embed/${encodeURIComponent(demoSlug)}`} className="h-9 px-3 rounded-lg bg-gray-950 text-white text-xs font-bold flex items-center gap-1.5 hover:bg-gray-800"><ExternalLink size={14}/> Demo</a><button onClick={()=>onNavigateToContact?onNavigateToContact(bot.name):(window.location.href='/?tab=contact&chatbot='+encodeURIComponent(bot.name))} className="h-9 px-3 rounded-lg bg-blue-600 text-white text-xs font-bold flex items-center gap-1.5 hover:bg-blue-700"><ShoppingCart size={14}/> Get Started</button></div>
   </div>
   {botPrices.length>0&&<div className="mt-4 pt-4 border-t text-xs text-gray-500 flex flex-wrap gap-2">{botPrices.slice(0,3).map(p=><span key={p.plan_name} className={p.highlighted?'font-bold text-blue-700':''}>{p.plan_name}: {'$'}{p.monthly_price}/mo</span>)}</div>}
  </article>})}</div>
 </section>;
};