import React, { useEffect, useMemo, useState } from 'react';
import { Bot, ExternalLink, ShoppingCart, Headphones, Target, Building2, Package, Wrench, LifeBuoy, CalendarCheck, CircleHelp, Store, ShoppingCart as CartIcon, House, Hotel, Plane, Utensils, Stethoscope, GraduationCap, WalletCards, ShieldCheck, Laptop, CloudCog, BriefcaseBusiness, Megaphone, UsersRound, Truck, CarFront, Scale, Dumbbell, UtensilsCrossed, X, LoaderCircle, Search } from 'lucide-react';
import { callBackend } from '../lib/backendApi';

const SUPABASE_URL = 'https://tlkmcfpzfdokcnyyvkov.supabase.co';
const SUPABASE_KEY = 'sb_publishable_-gNvioLExBonu8hGuWa8lQ_eIWmhMn6';

type Chatbot={id:string;name:string;slug:string;description?:string|null;enabled:boolean;embed_code?:string|null;logo_url?:string|null;brand_color?:string|null};
type Price={chatbot_id:string;plan_name:string;monthly_price:number;annual_price:number;highlighted?:boolean;enabled:boolean;description?:string;features?:string[]};

type OrderForm = { name:string; email:string; phone:string; company:string; website:string; message:string };
const emptyForm:OrderForm={name:'',email:'',phone:'',company:'',website:'',message:''};

function getDemoSlug(bot:Chatbot){const code=bot.embed_code||'';const match=code.match(/data-chatbot\s*=\s*["']([^"']+)["']/i);return match?.[1]||bot.slug;}

const categories=['All chatbots','Sales','Customer Support','Booking','E-commerce','Business','Other'];
function getCategory(bot:Chatbot){const value=(bot.name+' '+(bot.description||'')).toLowerCase();if(/booking|appointment|reservation|schedule|hotel|travel/.test(value))return 'Booking';if(/ecommerce|e-commerce|retail|shop|product|store|cart|restaurant|food/.test(value))return 'E-commerce';if(/support|customer care|helpdesk|help desk|service desk|faq|healthcare|tech support/.test(value))return 'Customer Support';if(/sales|leadgen|marketing|conversion|sell/.test(value))return 'Sales';if(/business|advisor|agency|finance|insurance|real estate|legal|fitness|education|logistics|automotive|hr /.test(value))return 'Business';return 'Other';}

const iconMap:Record<string,any>={'Customer Care Pro':Headphones,'Sales Assistant':Target,'LeadGen AI':Target,'Business Advisor':Building2,'Product Expert':Package,'Service Desk AI':Wrench,'Support Hero':LifeBuoy,'Booking Assistant':CalendarCheck,'FAQ Master':CircleHelp,'Retail Assistant':Store,'Ecommerce Guide':CartIcon,'Real Estate Advisor':House,'Hotel Concierge':Hotel,'Travel Planner':Plane,'Restaurant Host':Utensils,'Healthcare Reception':Stethoscope,'Education Advisor':GraduationCap,'Finance Support':WalletCards,'Insurance Assistant':ShieldCheck,'Tech Support AI':Laptop,'SaaS Sales Bot':CloudCog,'Agency Consultant':BriefcaseBusiness,'Marketing Assistant':Megaphone,'HR Helpdesk':UsersRound,'Logistics Assistant':Truck,'Automotive Advisor':CarFront,'Legal Reception':Scale,'Fitness Coach':Dumbbell,'Restaurant Sales Bot':UtensilsCrossed};
const iconColors:Record<string,string>={'Customer Care Pro':'#2563eb','Sales Assistant':'#16a34a','LeadGen AI':'#7c3aed','Business Advisor':'#0f766e','Product Expert':'#ea580c','Service Desk AI':'#475569','Support Hero':'#0284c7','Booking Assistant':'#db2777','FAQ Master':'#4f46e5','Retail Assistant':'#c2410c','Ecommerce Guide':'#0891b2','Real Estate Advisor':'#059669','Hotel Concierge':'#9333ea','Travel Planner':'#2563eb','Restaurant Host':'#dc2626','Healthcare Reception':'#0d9488','Education Advisor':'#4f46e5','Finance Support':'#15803d','Insurance Assistant':'#0369a1','Tech Support AI':'#334155','SaaS Sales Bot':'#7c3aed','Agency Consultant':'#b45309','Marketing Assistant':'#e11d48','HR Helpdesk':'#4f46e5','Logistics Assistant':'#ca8a04','Automotive Advisor':'#475569','Legal Reception':'#1e40af','Fitness Coach':'#16a34a','Restaurant Sales Bot':'#dc2626'};

export const ChatbotCatalog:React.FC<{onNavigateToContact?:(chatbotName:string)=>void}>=()=> {
 const[bots,setBots]=useState<Chatbot[]>([]),[prices,setPrices]=useState<Price[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[buyBot,setBuyBot]=useState<Chatbot|null>(null),[selectedPlan,setSelectedPlan]=useState(''),[billing,setBilling]=useState<'monthly'|'annual'>('monthly');
 const[form,setForm]=useState<OrderForm>(emptyForm),[submitting,setSubmitting]=useState(false),[orderError,setOrderError]=useState(''),[submitted,setSubmitted]=useState(false);\n const[searchQuery,setSearchQuery]=useState(''),[category,setCategory]=useState('All chatbots');
 useEffect(()=>{const load=async()=>{try{const headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY};const[botRes,priceRes]=await Promise.all([fetch(SUPABASE_URL+'/rest/v1/chatbots?select=id,name,slug,description,enabled,embed_code,logo_url,brand_color&enabled=eq.true&order=created_at.desc',{headers}),fetch(SUPABASE_URL+'/rest/v1/chatbot_prices?select=chatbot_id,plan_name,monthly_price,annual_price,highlighted,enabled,description,features&enabled=eq.true&order=sort_order.asc',{headers})]);if(!botRes.ok||!priceRes.ok)throw new Error('Could not load chatbots');setBots(await botRes.json());setPrices(await priceRes.json());}catch{setError('Chatbots could not be loaded right now.')}finally{setLoading(false)}};void load()},[]);\n const visibleBots=useMemo(()=>bots.filter(bot=>{const matchesCategory=category==='All chatbots'||getCategory(bot)===category;const text=(bot.name+' '+(bot.description||'')).toLowerCase();return matchesCategory&&text.includes(searchQuery.trim().toLowerCase())}),[bots,category,searchQuery]);
 const selectedPrice=buyBot&&selectedPlan?prices.find(p=>p.chatbot_id===buyBot.id&&p.plan_name===selectedPlan):undefined;
 const openBuy=(bot:Chatbot)=>{setBuyBot(bot);setSelectedPlan(prices.find(p=>p.chatbot_id===bot.id)?.plan_name||'');setBilling('monthly');setForm(emptyForm);setOrderError('');setSubmitted(false)};
 const closeBuy=()=>{if(!submitting){setBuyBot(null);setOrderError('')}};
 const submitOrder=async(e:React.FormEvent)=>{e.preventDefault();if(!buyBot)return;setOrderError('');setSubmitting(true);try{const payload:Record<string,unknown>={action:'lead',slug:buyBot.slug,name:form.name,email:form.email,phone:form.phone,company:form.company,company_website:form.website,chatbot_name:buyBot.name,order_type:'Pricing order',primary_goal:'Purchase chatbot',message:form.message||'Order request from the chatbot demo card.'};if(selectedPlan){payload.plan_name=selectedPlan;payload.billing_type=billing;const plan=prices.find(p=>p.chatbot_id===buyBot.id&&p.plan_name===selectedPlan);if(plan)payload.requested_price=billing==='annual'?plan.annual_price:plan.monthly_price;}await callBackend(payload);setSubmitted(true)}catch(err){setOrderError(err instanceof Error?err.message:'Could not submit your order. Please try again.')}finally{setSubmitting(false)}};
 return <section className="px-4 sm:px-6 pt-5 pb-7">
  <div className="mb-5"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-[11px] font-bold uppercase tracking-wider">Available AI Chatbots</div><h2 className="font-headline text-2xl sm:text-3xl font-extrabold text-gray-900 mt-2">Choose a chatbot to test</h2><p className="mt-2 text-sm text-gray-600">Try a live demo or submit an order request for the chatbot you want.</p></div>
  <div className="mb-5 space-y-3"><label className="flex items-center gap-3 rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-sm"><Search size={18} className="shrink-0 text-gray-400"/><input aria-label="Search chatbots" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search by chatbot name or what it does..." className="w-full bg-transparent text-sm outline-none placeholder:text-gray-400"/></label><div className="flex flex-wrap gap-2" aria-label="Filter chatbot categories">{categories.map(item=><button key={item} type="button" onClick={()=>setCategory(item)} className={"rounded-full border px-3 py-2 text-xs font-semibold transition "+(category===item?"border-blue-600 bg-blue-600 text-white":"border-gray-200 bg-white text-gray-600 hover:border-blue-300 hover:text-blue-700")}>{item}</button>)}</div></div>
  {loading&&<div className="rounded-2xl bg-white border p-6 text-sm text-gray-500">Loading chatbots…</div>}
  {error&&<div className="rounded-2xl bg-red-50 border border-red-100 p-6 text-sm text-red-700">{error}</div>}
  {!loading&&!error&&bots.length===0&&<div className="rounded-2xl bg-white border p-6 text-sm text-gray-500">No enabled chatbots yet.</div>}
  {!loading&&!error&&bots.length>0&&visibleBots.length===0&&<div className="rounded-2xl bg-white border p-6 text-sm text-gray-500">No chatbots match your search. Try another keyword or choose All chatbots.</div>}
  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{visibleBots.map(bot=>{const botPrices=prices.filter(p=>p.chatbot_id===bot.id);const cheapest=botPrices.length?Math.min(...botPrices.map(p=>Number(p.monthly_price))):null;const demoSlug=getDemoSlug(bot);const Icon=iconMap[bot.name]||Bot;const iconColor=iconColors[bot.name]||bot.brand_color||'#111827';return <article key={bot.id} className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5 flex flex-col">
   <div className="flex items-start justify-between gap-3"><div className="w-14 h-14 rounded-2xl flex items-center justify-center overflow-hidden bg-white border-2 shadow-sm" style={{color:iconColor,borderColor:iconColor+"33",backgroundColor:iconColor+"0D"}}>{bot.logo_url?<img src={bot.logo_url} alt={bot.name} className="w-full h-full object-contain bg-white p-2"/>:<Icon size={30} strokeWidth={2.4}/>}</div><span className="text-[10px] font-bold uppercase tracking-wide text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">Live Demo</span></div>
   <h3 className="font-bold text-lg text-gray-900 mt-4">{bot.name}</h3><p className="text-sm text-gray-600 mt-1 min-h-[40px]">{bot.description||'AI chatbot for sales and customer support.'}</p>
   <div className="mt-4 flex items-end justify-between gap-3"><div>{cheapest!==null?<><span className="text-xs text-gray-500">Starting from</span><div className="font-extrabold text-xl text-gray-900">{'$'}{cheapest}<span className="text-xs font-medium text-gray-500">/mo</span></div></>:<span className="text-sm text-gray-500">Pricing available on request</span>}</div>
    <div className="flex gap-2"><a href={`/embed/${encodeURIComponent(demoSlug)}`} className="h-9 px-3 rounded-lg bg-gray-950 text-white text-xs font-bold flex items-center gap-1.5 hover:bg-gray-800"><ExternalLink size={14}/> Demo</a><button onClick={()=>openBuy(bot)} className="h-9 px-3 rounded-lg bg-blue-600 text-white text-xs font-bold flex items-center gap-1.5 hover:bg-blue-700"><ShoppingCart size={14}/> Buy</button></div>
   </div>
   {botPrices.length>0&&<div className="mt-4 pt-4 border-t text-xs text-gray-500 flex flex-wrap gap-2">{botPrices.slice(0,3).map(p=><span key={p.plan_name} className={p.highlighted?'font-bold text-blue-700':''}>{p.plan_name}: {'$'}{p.monthly_price}/mo</span>)}</div>}
  </article>})}</div>
  {buyBot&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/60 p-3 sm:p-5" role="dialog" aria-modal="true" aria-labelledby="buy-chatbot-title">
   <div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-7">
    <div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wider text-blue-600">Chatbot order</div><h2 id="buy-chatbot-title" className="mt-1 text-2xl font-extrabold text-slate-950">Buy {buyBot.name}</h2><p className="mt-1 text-sm text-slate-500">Submit your details. Our team will contact you to confirm the order and payment instructions.</p></div><button type="button" onClick={closeBuy} disabled={submitting} aria-label="Close order form" className="rounded-lg border p-2 text-slate-500 hover:bg-slate-50 disabled:opacity-50"><X size={18}/></button></div>
    {submitted?<div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><div className="font-bold text-emerald-900">Order request submitted!</div><p className="mt-2 text-sm text-emerald-800">Your request for {buyBot.name} has been saved. Our team will contact you soon.</p>{selectedPrice&&<div className="mt-3 rounded-lg border border-emerald-200 bg-white/70 p-3 text-sm text-emerald-900"><div className="font-semibold">{selectedPlan}</div><div>${Number(billing==='annual'?selectedPrice.annual_price:selectedPrice.monthly_price).toLocaleString()}/mo · billed {billing==='annual'?'annually':'monthly'}</div></div>}<button type="button" onClick={()=>setBuyBot(null)} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Done</button></div>:<form className="mt-5 space-y-3" onSubmit={submitOrder}>
     {orderError&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{orderError}</div>}
     <div><label htmlFor="buy-name" className="mb-1 block text-xs font-semibold text-slate-700">Full name *</label><input id="buy-name" required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Your full name"/></div>
     <div><label htmlFor="buy-email" className="mb-1 block text-xs font-semibold text-slate-700">Email address *</label><input id="buy-email" required type="email" maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="you@company.com"/></div>
     <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div><label htmlFor="buy-phone" className="mb-1 block text-xs font-semibold text-slate-700">Phone / WhatsApp</label><input id="buy-phone" maxLength={40} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="+92..."/></div><div><label htmlFor="buy-company" className="mb-1 block text-xs font-semibold text-slate-700">Company name</label><input id="buy-company" maxLength={160} value={form.company} onChange={e=>setForm({...form,company:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Your company"/></div></div>
     <div><label htmlFor="buy-website" className="mb-1 block text-xs font-semibold text-slate-700">Website (optional)</label><input id="buy-website" type="url" maxLength={500} value={form.website} onChange={e=>setForm({...form,website:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="https://example.com"/></div>
     {prices.some(p=>p.chatbot_id===buyBot.id)&&<div><label htmlFor="buy-plan" className="mb-1 block text-xs font-semibold text-slate-700">Choose a plan *</label><select id="buy-plan" required value={selectedPlan} onChange={e=>setSelectedPlan(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-blue-500"><option value="" disabled>Select a pricing plan</option>{prices.filter(p=>p.chatbot_id===buyBot.id).map(p=><option key={p.plan_name} value={p.plan_name}>{p.plan_name} — ${Number(billing==='annual'?p.annual_price:p.monthly_price).toLocaleString()}/mo{billing==='annual'?' · billed annually':''}</option>)}</select><div className="mt-3 flex gap-2"><button type="button" onClick={()=>setBilling('monthly')} className={`flex-1 rounded-xl border p-2.5 text-sm font-semibold ${billing==='monthly'?'border-blue-600 bg-blue-50 text-blue-700':'border-slate-200 text-slate-600'}`}>Monthly</button><button type="button" onClick={()=>setBilling('annual')} className={`flex-1 rounded-xl border p-2.5 text-sm font-semibold ${billing==='annual'?'border-blue-600 bg-blue-50 text-blue-700':'border-slate-200 text-slate-600'}`}>Annual</button></div></div>}
     <div><label htmlFor="buy-message" className="mb-1 block text-xs font-semibold text-slate-700">Order notes (optional)</label><textarea id="buy-message" rows={3} maxLength={2000} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className="w-full resize-y rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Tell us what you need..."/></div>
     <div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs leading-5 text-slate-600">No payment is taken through this form. Your order request will appear in the admin dashboard under Pricing Orders.</div>
     <button type="submit" disabled={submitting} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60">{submitting?<><LoaderCircle size={16} className="animate-spin"/>Submitting order…</>:'Submit order request'}{!submitting&&<ShoppingCart size={16}/>}</button>
    </form>}
   </div>
  </div>}
 </section>;
};
