import React, { useEffect, useState } from 'react';
import { callBackend } from '../lib/backendApi';
interface PricingScreenProps { onNavigateToContact: () => void; onOpenLiveChat: () => void; onShowToast: (title: string, message: string) => void; }
type Plan={plan_name:string;monthly_price:number;annual_price:number;description:string;features:string[];highlighted:boolean};
export const PricingScreen: React.FC<PricingScreenProps> = ({ onNavigateToContact, onShowToast }) => {
 const [isAnnual,setIsAnnual]=useState(true); const [openFaq,setOpenFaq]=useState<number|null>(0); const [plans,setPlans]=useState<Plan[]>([]);
 useEffect(()=>{ callBackend<{prices:Plan[]}>({action:'config',slug:'sales-chatbot'}).then(r=>setPlans(r.prices||[])).catch(()=>setPlans([])); },[]);
 const faqs=[['How does the human handoff work?','Visitors can request a human sales specialist and the conversation can be routed to your sales workflow.'],['Can the bot use our website or knowledge base?','Yes. Each chatbot can have its own prompt and knowledge configuration.'],['Can pricing be changed without editing the website?','Yes. Prices are stored in Supabase and the website loads them from the backend API.'],['Are API keys exposed to visitors?','No. AI provider secrets belong in Supabase Edge Function secrets, not in the browser.']];
 const handleSelectPlan=(name:string)=>name==='Enterprise'?onNavigateToContact():onShowToast('Free Trial Activated','Your 14-day trial of '+name+' has been initialized.');
 return <div className='flex flex-col w-full pb-10'><section className='px-4 sm:px-6 py-6'><div className='inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#eff6ff] text-[#1e40af]'><span className='w-2 h-2 rounded-full bg-[#0266ff]'/> <span className='text-[11px] font-bold uppercase tracking-wider'>Live Backend Pricing</span></div><h1 className='font-headline text-[26px] sm:text-[34px] text-[#111827] tracking-tight font-extrabold leading-[1.2] mt-2'>Simple, Volume-Aligned Plans</h1><p className='text-[14px] sm:text-[15px] text-[#4b5563]'>Prices are loaded from the Sales Chatbot backend. Change them in Supabase without changing frontend code.</p><div className='flex items-center gap-3 mt-3 bg-gray-100 p-1 rounded-xl'><button onClick={()=>setIsAnnual(false)} className={'px-3.5 py-1.5 rounded-lg text-xs font-bold '+(!isAnnual?'bg-white text-gray-900 shadow-xs':'text-gray-600')}>Monthly</button><button onClick={()=>setIsAnnual(true)} className={'px-3.5 py-1.5 rounded-lg text-xs font-bold '+(isAnnual?'bg-[#d61616] text-white shadow-xs':'text-gray-600')}>Annual <span className='text-[10px] bg-white/20 px-1.5 py-0.5 rounded-full'>Save 20%</span></button></div></section>
 <section className='px-4 sm:px-6 pb-6 space-y-4'>{plans.map(plan=>{const price=isAnnual?plan.annual_price:plan.monthly_price;return <div key={plan.plan_name} className={'rounded-2xl p-5 border '+(plan.highlighted?'bg-white border-[#d61616] shadow-lg ring-2 ring-[#d61616]/10':'bg-white border-gray-200 shadow-xs')}><div className='flex items-center justify-between'><div><span className={'text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full '+(plan.highlighted?'bg-[#fee2e2] text-[#991b1b]':'bg-gray-100 text-gray-700')}>{plan.highlighted?'Most Popular':plan.plan_name}</span><h3 className='font-headline text-xl font-bold text-gray-900 mt-1'>{plan.plan_name}</h3></div><div className='text-right'><div className='flex items-baseline gap-0.5 justify-end'><span className='font-headline text-3xl font-extrabold text-gray-900 tabular-nums'>$'+price+'</span><span className='text-xs text-gray-500 font-medium'>/mo</span></div><span className='text-[10px] text-gray-400'>{isAnnual?'Billed annually':'Billed monthly'}</span></div></div><p className='text-xs text-gray-600 mt-2.5 leading-relaxed'>{plan.description}</p><div className='my-4 border-t border-gray-100 pt-3'><span className='text-[11px] font-bold text-gray-900 block mb-2'>What's included:</span><ul className='space-y-1.5 text-xs text-gray-700'>{plan.features.map((f,i)=><li key={i} className='flex items-center gap-2'><span className='material-symbols-outlined text-[#10b981] text-[16px]'>check_circle</span>{f}</li>)}</ul></div><button onClick={()=>handleSelectPlan(plan.plan_name)} className={'w-full h-11 rounded-xl text-xs sm:text-sm font-bold '+(plan.highlighted?'bg-[#d61616] hover:bg-[#bd1313] text-white':'bg-gray-900 hover:bg-gray-800 text-white')}>{plan.plan_name==='Enterprise'?'Talk with AI Architects':plan.plan_name==='Growth'?'Start Free Trial':'Start 14-Day Free Trial'} <span className='material-symbols-outlined text-[16px]'>arrow_forward</span></button></div>})}</section>
 <section className='px-4 sm:px-6 py-4'><div className='bg-white rounded-2xl p-5 border border-gray-200 shadow-xs'><h3 className='font-headline text-lg font-bold text-gray-900 mb-3'>Frequently Asked Questions</h3><div className='divide-y divide-gray-100'>{faqs.map((f,i)=>{const open=openFaq===i;return <div key={i} className='py-3'><button onClick={()=>setOpenFaq(open?null:i)} className='w-full flex items-center justify-between text-left gap-2'><span className='text-xs sm:text-sm font-bold text-gray-900'>{f[0]}</span><span className={'material-symbols-outlined text-gray-400 text-[18px] '+(open?'rotate-180 text-gray-700':'')}>expand_more</span></button>{open&&<p className='text-xs text-gray-600 mt-2 leading-relaxed'>{f[1]}</p>}</div>})}</div><div className='mt-4 pt-3 border-t border-gray-100 flex items-center justify-between'><span className='text-xs text-gray-500'>Still have questions?</span><button onClick={onNavigateToContact} className='text-xs font-bold text-[#d61616] hover:underline'>Contact our sales engineering team →</button></div></div></section>
 </div>; };