import React,{useEffect,useState} from 'react';
import {callBackend} from '../lib/backendApi';
import {Check,ArrowRight,Sparkles,X,LoaderCircle} from 'lucide-react';

interface PricingScreenProps{onNavigateToContact:()=>void;onOpenLiveChat:()=>void;onShowToast:(title:string,message:string)=>void}
type Plan={plan_name:string;monthly_price:number;annual_price:number;description:string;features:string[];highlighted:boolean};
type OrderForm={name:string;email:string;phone:string;company:string;website:string;message:string};
const emptyForm:OrderForm={name:'',email:'',phone:'',company:'',website:'',message:''};

export const PricingScreen:React.FC<PricingScreenProps>=({onNavigateToContact,onOpenLiveChat,onShowToast})=>{
 const[annual,setAnnual]=useState(true),[plans,setPlans]=useState<Plan[]>([]),[faq,setFaq]=useState<number|null>(0);
 const[chatbotName,setChatbotName]=useState('Sales Chatbot');
 const[orderPlan,setOrderPlan]=useState<Plan|null>(null),[billing,setBilling]=useState<'monthly'|'annual'>('annual');
 const[form,setForm]=useState<OrderForm>(emptyForm),[submitting,setSubmitting]=useState(false),[submitted,setSubmitted]=useState(false),[footerPage,setFooterPage]=useState<string|null>(null);
 useEffect(()=>{callBackend<{prices:Plan[];chatbot?:{name?:string}}>({action:'config',slug:'sales-chatbot'}).then(r=>{setPlans(r.prices||[]);if(r.chatbot?.name)setChatbotName(r.chatbot.name)}).catch(()=>setPlans([]))},[]);
 const faqs=[['Can I change plans?','Yes. Choose the plan that fits your business as you grow.'],['Can I use my own website content?','Yes. Your chatbot can be configured for your business and knowledge.'],['How do I pay?','Submit your order request. Our team will contact you with bank transfer instructions and confirm payment manually.'],['Are AI keys secure?','Yes. Provider keys stay on the backend, not in the browser.']];
 const footerContent:Record<string,{title:string;body:string[]}>= {
  about:{title:'About our AI chatbots',body:['We help businesses use AI chatbots to answer customer questions, support visitors, and capture sales enquiries.','Choose a plan, test a chatbot in the Free Demo, then submit an order request to discuss setup for your business.']},
  terms:{title:'Terms of Service',body:['By submitting an order request, you agree to provide accurate contact details and use the chatbot service lawfully.','Submitting the form does not charge you or activate a paid plan. Our team will confirm the scope, price, and payment instructions with you first.']},
  privacy:{title:'Privacy Policy',body:['We use the details you submit, such as your name, email, company, and message, to respond to your enquiry and process your order request.','Please do not submit passwords, payment card details, or other sensitive information in the enquiry form. Contact us if you need help with a privacy request.']},
  refund:{title:'Refund Policy',body:['No payment is taken when you submit a pricing order request. Payment arrangements and any applicable refund terms should be confirmed with our team before you pay.','If you have already paid and need help, contact our team with your order details so we can review your request.']},
  careers:{title:'Careers',body:['Interested in working with us on AI chatbots or automation? Send us a message through Contact Experts and tell us about your experience and the role you are interested in.']},
  voice:{title:'AI Voice Agents',body:['Voice agents can help answer spoken customer questions and guide callers through common requests. Tell us your use case and we will discuss the right setup.']},
  support:{title:'Support Bots',body:['Support bots answer common questions, explain services, and help customers find the next step. They can be configured around your approved business information.']},
  sales:{title:'Sales Agents',body:['Sales agents help visitors understand products, compare plans, and send purchase enquiries to your team. Try the Free Demo before choosing a plan.']},
  workflows:{title:'AI Workflows',body:['AI workflows can help connect repetitive business tasks and customer conversations. Contact us with the steps you want to automate.']},
  rag:{title:'RAG Knowledge Systems',body:['Knowledge-based chatbots can use your business documents and approved content to answer relevant questions. We can help you discuss which documents and setup fit your needs.']},
  help:{title:'Help & getting started',body:['1. Open Free Demo to test an available chatbot.','2. Visit Pricing and choose Monthly or Annual billing.','3. Select Get started and submit your contact details.','4. Our team will contact you with next steps and bank-transfer instructions. No payment is taken in the order form.']}
 };
 const openOrder=(plan:Plan)=>{setOrderPlan(plan);setBilling(annual?'annual':'monthly');setSubmitted(false);setForm(emptyForm)};
 const submitOrder=async(e:React.FormEvent)=>{e.preventDefault();if(!orderPlan)return;setSubmitting(true);try{const price=billing==='annual'?Number(orderPlan.annual_price):Number(orderPlan.monthly_price);await callBackend({action:'lead',name:form.name,email:form.email,phone:form.phone,company:form.company,company_website:form.website,chatbot_name:chatbotName,plan_name:orderPlan.plan_name,requested_price:price,billing_type:billing,payment_method:'bank_transfer',payment_status:'awaiting_instructions',order_status:'New',order_type:'Pricing order',primary_goal:'Purchase chatbot plan',message:form.message||'Order submitted from the Pricing page.'});setSubmitted(true);onShowToast('Order request received','Your selected plan has been sent to our team.');}catch(err){onShowToast('Could not submit order',err instanceof Error?err.message:'Please try again.')}finally{setSubmitting(false)}};
 return <div className="w-full bg-white pb-10">
 <section className="px-5 sm:px-8 lg:px-12 pt-10 pb-8"><div className="max-w-6xl mx-auto"><span className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-wider text-blue-700"><Sparkles size={13}/>Simple pricing</span><h1 className="mt-4 font-headline text-3xl sm:text-5xl font-extrabold tracking-tight text-gray-950">Choose your AI chatbot plan.</h1><p className="mt-3 max-w-xl text-base text-gray-600">Start small, test your chatbot, and scale when your business grows.</p><div className="mt-6 inline-flex rounded-xl bg-gray-100 p-1"><button onClick={()=>setAnnual(false)} className={'px-4 py-2 rounded-lg text-xs font-bold '+(!annual?'bg-white text-gray-950 shadow-sm':'text-gray-500')}>Monthly</button><button onClick={()=>setAnnual(true)} className={'px-4 py-2 rounded-lg text-xs font-bold '+(annual?'bg-gray-950 text-white':'text-gray-500')}>Annual <span className="ml-1 opacity-70">Save 20%</span></button></div></div></section>
 <section className="bg-gray-50 border-y border-gray-100 px-5 sm:px-8 lg:px-12 py-8"><div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-5">{plans.map((plan,index)=>{const price=annual?plan.annual_price:plan.monthly_price;return <article key={plan.plan_name} className={'rounded-2xl p-6 border '+(['bg-blue-50/70','bg-white','bg-indigo-50/60'][index%3])+' '+(plan.highlighted?'border-blue-500 shadow-lg ring-2 ring-blue-500/10':'border-gray-200 shadow-sm')}>{plan.highlighted&&<span className="inline-flex mb-3 rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-blue-700">Most popular</span>}<h2 className="text-xl font-bold text-gray-950">{plan.plan_name}</h2><p className="mt-2 min-h-[40px] text-sm text-gray-600">{plan.description}</p><div className="mt-5"><span className="text-4xl font-extrabold text-gray-950">${price}</span><span className="text-sm text-gray-500">/mo</span></div><p className="mt-1 text-[11px] text-gray-400">{annual?'Billed annually':'Billed monthly'}</p><ul className="mt-5 space-y-2.5 border-t pt-5">{(plan.features||[]).slice(0,5).map((f,i)=><li key={i} className="flex gap-2 text-sm text-gray-700"><Check size={16} className="mt-0.5 shrink-0 text-emerald-500"/>{f}</li>)}</ul><button onClick={()=>openOrder(plan)} className={'mt-6 w-full h-11 rounded-xl flex items-center justify-center gap-2 text-sm font-bold '+(plan.highlighted?'bg-blue-600 hover:bg-blue-700 text-white':'bg-gray-950 hover:bg-gray-800 text-white')}>Get started<ArrowRight size={15}/></button></article>})}</div>{plans.length===0&&<div className="max-w-2xl mx-auto rounded-2xl bg-white border p-6 text-center text-sm text-gray-500">Pricing is temporarily unavailable.</div>}</section>
 <section className="px-5 sm:px-8 lg:px-12 py-8"><div className="max-w-3xl mx-auto"><h2 className="font-headline text-2xl font-bold text-gray-950">Quick answers</h2><div className="mt-4 divide-y border-y">{faqs.map((f,i)=>{const open=faq===i;return <div key={i}><button onClick={()=>setFaq(open?null:i)} className="w-full py-4 flex justify-between text-left text-sm font-semibold text-gray-900">{f[0]}<span>{open?'−':'+'}</span></button>{open&&<p className="pb-4 pr-8 text-sm leading-6 text-gray-600">{f[1]}</p>}</div>})}</div><button onClick={onNavigateToContact} className="mt-5 text-sm font-bold text-blue-600">Have a question? Contact us <ArrowRight size={14} className="inline"/></button></div></section>
 <footer className="mt-8 border-t border-blue-100 bg-white px-5 py-9 text-slate-900 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-6xl grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Sparkles size={18}/></span><span className="text-lg font-extrabold">AI Chatbots</span></div><p className="mt-3 max-w-xs text-sm leading-6 text-slate-300">Helpful AI assistants for sales, support, and business workflows.</p><button onClick={()=>setFooterPage('help')} className="mt-4 rounded-lg bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700 hover:bg-blue-100">Help & getting started</button></div><div><h3 className="text-sm font-bold text-white">Company</h3><div className="mt-3 flex flex-col items-start gap-2.5 text-sm text-slate-600">{[['About','about'],['Terms of Service','terms'],['Privacy Policy','privacy'],['Refund Policy','refund'],['Careers','careers']].map(([label,key])=><button key={key} onClick={()=>setFooterPage(key)} className="text-left hover:text-white hover:underline">{label}</button>)}</div></div><div><h3 className="text-sm font-bold text-white">Solutions</h3><div className="mt-3 flex flex-col items-start gap-2.5 text-sm text-slate-300">{[['AI Voice Agents','voice'],['Support Bots','support'],['Sales Agents','sales'],['Workflows','workflows'],['RAG Systems','rag']].map(([label,key])=><button key={key} onClick={()=>setFooterPage(key)} className="text-left hover:text-white hover:underline">{label}</button>)}</div></div><div><h3 className="text-sm font-bold text-white">Contact & Support</h3><p className="mt-3 text-sm leading-6 text-slate-600">Need help choosing a chatbot or placing an order? Talk to our team.</p><button onClick={onNavigateToContact} className="mt-3 text-sm font-semibold text-blue-700 hover:text-blue-900">Contact experts →</button><button onClick={onOpenLiveChat} className="mt-2 block text-sm text-slate-600 hover:text-slate-900">Open live chat</button><button onClick={onNavigateToContact} className="mt-2 block text-sm text-slate-300 hover:text-white">Support / order help</button><a href="mailto:sales@chatbot.com" className="mt-2 block text-sm text-slate-300 hover:text-white">sales@chatbot.com</a></div></div><div className="mx-auto mt-8 max-w-6xl border-t border-gray-200 pt-5 text-xs text-slate-500">© {new Date().getFullYear()} AI Chatbots. All rights reserved.</div></footer>
 {footerPage&&footerContent[footerPage]&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-labelledby="footer-info-title"><div className="w-full max-w-lg rounded-2xl bg-white p-6 text-slate-900 shadow-2xl"><div className="flex items-start justify-between gap-4"><h2 id="footer-info-title" className="text-xl font-extrabold">{footerContent[footerPage].title}</h2><button onClick={()=>setFooterPage(null)} aria-label="Close information" className="rounded-lg border px-2.5 py-1 text-slate-500 hover:bg-slate-50">✕</button></div><div className="mt-4 space-y-3 text-sm leading-6 text-slate-600">{footerContent[footerPage].body.map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>{setFooterPage(null);onNavigateToContact()}} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Contact support</button><button onClick={()=>setFooterPage(null)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Close</button></div></div></div>}
 {orderPlan&&<div className="fixed inset-0 z-[100] flex items-center justify-center overflow-y-auto bg-slate-950/60 p-3 sm:p-6" role="dialog" aria-modal="true" aria-labelledby="pricing-order-title"><div className="my-auto w-full max-w-xl rounded-3xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Place your order</p><h2 id="pricing-order-title" className="mt-1 text-2xl font-extrabold text-slate-950">{submitted?'Request received':orderPlan.plan_name+' plan'}</h2><p className="mt-1 text-sm text-slate-500">{submitted?'Our team will contact you to confirm your order and payment.':'Complete this form and your order will appear in our dashboard.'}</p></div><button onClick={()=>setOrderPlan(null)} aria-label="Close form" className="rounded-xl border p-2 text-slate-500 hover:bg-slate-50"><X size={18}/></button></div>
 {!submitted?<form onSubmit={submitOrder} className="mt-5 space-y-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="flex items-center justify-between gap-3"><span className="font-bold text-slate-900">{orderPlan.plan_name}</span><span className="text-xl font-extrabold text-slate-950">${billing==='annual'?orderPlan.annual_price:orderPlan.monthly_price}<span className="text-xs font-medium text-slate-500">/{billing==='annual'?'mo, billed yearly':'month'}</span></span></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setBilling('monthly')} className={'rounded-xl border p-2.5 text-sm font-bold '+(billing==='monthly'?'border-blue-600 bg-white text-blue-700':'border-transparent bg-blue-100 text-slate-600')}>Monthly</button><button type="button" onClick={()=>setBilling('annual')} className={'rounded-xl border p-2.5 text-sm font-bold '+(billing==='annual'?'border-blue-600 bg-white text-blue-700':'border-transparent bg-blue-100 text-slate-600')}>Annual</button></div></div>
 <div className="grid gap-3 sm:grid-cols-2"><input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name *" className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><input required type="email" maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email address *" className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><input value={form.phone} maxLength={40} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone / WhatsApp" className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><input value={form.company} maxLength={160} onChange={e=>setForm({...form,company:e.target.value})} placeholder="Company name" className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/></div>
 <input type="url" value={form.website} maxLength={500} onChange={e=>setForm({...form,website:e.target.value})} placeholder="Company website (https://...)" className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><textarea rows={3} maxLength={2000} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Anything we should know? (optional)" className="w-full resize-y rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><div className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-semibold text-slate-900">Payment: Bank transfer / manual confirmation</p><p className="mt-1 text-xs text-slate-500">No payment is taken here. We will send instructions and confirm your payment manually.</p></div><button disabled={submitting} type="submit" className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60">{submitting?<><LoaderCircle size={16} className="animate-spin"/>Submitting…</>:'Submit order request →'}</button></form>:<div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-sm text-emerald-900"><p className="font-bold">Your order request has been saved.</p><p className="mt-1">Our team will review your {orderPlan.plan_name} plan request and contact you about payment.</p><button onClick={()=>setOrderPlan(null)} className="mt-4 rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Done</button></div>}</div></div>}
 </div>;
};
